# Generated by Django 4.1 on 2025-01-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangashubbr', '0002_fotografia_categoria_alter_fotografia_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('PLANETA', 'Planeta'), ('ESTRELA', 'Estrela'), ('GALÁXIA', 'Galáxia'), ('NEBULOSA', 'Nebulosa')], default='', max_length=100),
        ),
    ]
