# Generated by Django 4.1 on 2025-01-26 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangashubbr', '0003_fotografia_publicada_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_fotografia',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('GALÁXIA', 'Galáxia'), ('PLANETA', 'Planeta'), ('NEBULOSA', 'Nebulosa'), ('ESTRELA', 'Estrela')], default='', max_length=100),
        ),
    ]
